controller_frequency: 9
recovery_behaviour_enabled: true

TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.1
  max_vel_theta: 2.5
  min_in_place_vel_theta: 0.2
  meter_scoring: true

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.8

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.3

  holonomic_robot: false
