TrajectoryPlannerROS:
  max_vel_x: 6.0
  min_vel_x: 0.01
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.0
  meter_scoring: true

  acc_lim_x: 0.8
  acc_lim_y: 2.5
  acc_lim_theta: 0.5

  yaw_goal_tolerance: 1.0
  xy_goal_tolerance: 0.5

  holonomic_robot: false
