recovery_behavior_enabled: true

TrajectoryPlannerROS:

  max_vel_x: 0.6
  min_vel_x: 0.15
  min_vel_theta: -2.0
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.55
  escape_vel: -0.15
  meter_scoring: true

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 2.0

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.3

  holonomic_robot: false
