obstacle_range: 12.0
raytrace_range: 12.0
footprint: [[-0.50, -0.40], [-0.50, 0.40], [0.50, 0.40], [0.50, -0.40]]
#robot_radius: ir_of_robot
inflation_radius: 0.4

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: laser, data_type: PointCloud, topic: /scan, marking: true, clearing: true}
